name: randomjokes
description: Flutter app that displays random 'haha' jokes.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/laugh.png"
  adaptive_icon_background: "#FFFFFF"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/laugh.png
  android_gravity: center
  fullscreen: true
  ios: false
  web: false


flutter:

  uses-material-design: true

  assets:
    - assets/images/laugh.png

  fonts:
    - family: RubikBubbles
      fonts:
        - asset: assets/fonts/RubikBubbles-Regular.ttf

    - family: RubikGlitch
      fonts:
        - asset: assets/fonts/RubikGlitch-Regular.ttf
    
    - family: RubikMicrobe
      fonts:
        - asset: assets/fonts/RubikMicrobe-Regular.ttf
    
    - family: RubikMoonrocks
      fonts:
        - asset: assets/fonts/RubikMoonrocks-Regular.ttf
    
    - family: RubikWetPaint
      fonts:
        - asset: assets/fonts/RubikWetPaint-Regular.ttf