name: randomjokes
description: Flutter app that displays random 'haha' jokes.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: RubikBubbles
      fonts:
        - asset: assets/fonts/RubikBubbles-Regular.ttf

    - family: RubikGlitch
      fonts:
        - asset: assets/fonts/RubikGlitch-Regular.ttf
    
    - family: RubikMicrobe
      fonts:
        - asset: assets/fonts/RubikMicrobe-Regular.ttf
    
    - family: RubikMoonrocks
      fonts:
        - asset: assets/fonts/RubikMoonrocks-Regular.ttf
    
    - family: RubikWetPaint
      fonts:
        - asset: assets/fonts/RubikWetPaint-Regular.ttf